---
- name: Capture the samba initial settings
  hosts: [ 'tkl_fileserver' ]
  gather_facts: False
  become: True

  tasks:
    - name: samba pre settings
      shell: testparm -sv | grep -v 'netbios name'
      register: samba_pre

