---
- name: Compare the samba final settings
  hosts: [ 'tkl_fileserver' ]
  gather_facts: False
  become: True

  tasks:
    - name: samba post settings
      shell: testparm -sv | grep -v 'netbios name' | grep -v 'null passwords = Yes' | grep -v 'restrict anonymous = 0' | grep -v 'vfs objects = '
      register: samba_post

    - name: debug samba settings
      debug:
        msg: '{{ item.0 + " : " + item.1 }}'
      with_together:
        - '{{ samba_pre.stdout_lines }}'
        - '{{ samba_post.stdout_lines }}'
      when: samba_pre.stdout_lines != samba_post.stdout_lines and item.0 != item.1

    - name: compare samba settings
      assert:
        that: "samba_pre.stdout_lines == samba_post.stdout_lines"
        msg: samba configuration is different from initial

