---

- name: Update appliance packages and restart
  hosts: tkl_core
  gather_facts: False
  become: True

  tasks:
    - name: Wait for appliance container to be available
      wait_for_connection:
        delay: 5

    - name: Set fqdn for container in hostname
      lineinfile:
        path: /etc/hostname
        regexp: '{{ app_name }}'
        line: '{{ app_name }}.local.lxc'
        state: present

    - name: Set fqdn for container in hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^([0-9.]*) {{ app_name }}'
        line: '\1 {{ app_name }}.local.lxc {{ app_name }}'
        backrefs: yes
        state: present

    - name: Upgrade all installed packages
      shell: apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -q -y upgrade

    - name: Restart container
      command: shutdown -r now

    - name: Wait for appliance container to reboot
      wait_for_connection:
        delay: 20
